{% set name = "pdf-reports" %}
{% set version = "3.4.1-fork" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Edinburgh-Genome-Foundry/pdf_reports/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3a79ed028979c4978f95fefa41729f28de20e5cf7c68b35d42461a16f1cf2dbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('pdf-reports', max_pin="x.x") }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pypugjs
    - jinja2 <3.1.0
    - weasyprint
    - beautifulsoup4
    - pandas
    - markdown
    - backports.functools_lru_cache

test:
  source_files:
    - tests/
  imports:
    - pdf_reports
  requires:
    - python {{ python_min }}
    - libsass
    - matplotlib-base
    - pypdf
    - pytest
    - pytest-cov
    - pytest-mock
  commands:
    - pytest tests/


about:
  home: https://github.com/Edinburgh-Genome-Foundry/pdf_reports
  summary: "pdf_reports developed by EGF to create nice-looking PDF reports from HTML or Pug templates."
  license: MIT
  license_file: LICENCE.txt


extra:
  recipe-maintainers:
    - breakthewall
    - tduigou
    - ramez17khaled
